services:
  nats-server:
    image: nats:2.10.16-alpine3.19
    ports:
      - 8222:8222

  gateway:
    build: ./gateway
    ports:
      - 3000:3000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: pnpm start:dev
    env_file:
      - ./gateway/.env
    environment:
      - NATS_SERVERS=nats://nats-server:4222

  products:
    depends_on:
      - products-db
    build: ./products
    volumes:
      - ./products/src:/usr/src/app/src
    command: pnpm start:dev
    env_file:
      - ./products/.env
    environment:
      - DATABASE_URL=postgresql://postgres:123123@products-db:5432/products
      - NATS_SERVERS=nats://nats-server:4222

  products-db:
    container_name: products_db
    image: postgres:16.3
    restart: always
    volumes:
      - ./products/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./products/.env
